---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-collector-deployment
  labels:
    app: test-collector
    component: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-collector
      version: v1
  template:
    metadata:
      labels:
        app: test-collector
        component: main
    spec:
      containers:
        - name: test-collector
          image: index.docker.io/ahauger/test-collector:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 128Mi
              cpu: 100m
          ports:
            - containerPort: 4000
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test-collector-service
  labels:
    app: test-collector
spec:
  selector:
    app: test-collector
  type: NodePort
  ports:
  - port: 80
    nodePort: 31364
    targetPort: 4000
    protocol: TCP
    name: http