on:
  push:
    branches: 
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Caching
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-test-collector-cache
          key: ${{ runner.os }}-buildx-test-collector-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-test-collector-

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push test-collector
        run: |
          docker buildx build -f ./Dockerfile --cache-from=type=local,src=/tmp/.buildx-test-collector-cache --cache-to=type=local,dest=/tmp/.buildx-test-collector-cache-new -t index.docker.io/ahauger/test-collector:latest --push .

      - name: Replace docker cache
        run: |
          rm -rf /tmp/.buildx-test-collector-cache
          mv /tmp/.buildx-test-collector-cache-new /tmp/.buildx-test-collector-cache